trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

stages:
- stage: Build
  jobs:
  - job: InstallJob
    steps:
    - bash: echo install packages
    - bash: npm install
    - bash: ls $(System.DefaultWorkingDirectory)
  - job: BuildJob
    dependsOn: InstallJob
    steps:
    - bash: echo build app
    - bash: cd $(System.DefaultWorkingDirectory)
    - bash: ls 
- stage: Deploy
  dependsOn: Build
  jobs:
  - job: DeployJob
    steps:
    - bash: echo DeployJob