trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

stages:
- stage: Build
  jobs:
  - job: InstallJob
    steps:
    - bash: echo install packages
    - bash: npm install
    - task: CopyFiles@2
      inputs:
        SourceFolder: '$(System.DefaultWorkingDirectory)'
        Contents: '**'
        TargetFolder: '$(Build.ArtifactStagingDirectory)'
    - bash: ls $(Build.ArtifactStagingDirectory)
    - task: PublishBuildArtifacts@1
      inputs:
        PathtoPublish: '$(Build.ArtifactStagingDirectory)'
        ArtifactName: 'drop'
        publishLocation: 'Container'
  - job: BuildJob
    dependsOn: InstallJob
    steps:
    - bash: echo build app
    - bash: ls $(Build.ArtifactStagingDirectory)
- stage: Deploy
  dependsOn: Build
  jobs:
  - job: DeployJob
    steps:
    - bash: echo DeployJob