trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

stages:
- stage: Build
  jobs:
  - job: InstallJob
    steps:
    - bash: echo install packages
    - bash: npm install
  - job: BuildJob
    dependsOn: InstallJob
    steps:
    - bash: echo build app
- stage: Deploy
  dependsOn: Build
  jobs:
  - job: DeployJob
    steps:
    - bash: echo DeployJob